/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: driggleman (https://sketchfab.com/driggleman)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/maple-tree-68bea58fd9a549a99cfa5d1c739c97a8
Title: Maple Tree
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

import treemodel from '../assets/Models/Tree.glb'

const Tree = (props) => {

  const { nodes, materials } = useGLTF(treemodel);

  return (
<group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Tree_1.geometry} material={materials.Leaf} />
      <mesh castShadow receiveShadow geometry={nodes.Tree_2.geometry} material={materials.Trunk} />
      <mesh castShadow receiveShadow geometry={nodes.Tree_3.geometry} material={materials.Branch} />
    </group>
  )
}

useGLTF.preload(treemodel)

export default Tree;